name: Update

on:
  schedule:
    - cron:  '0 15 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-resizer-5_1_1
    - run: |
        if ! command -v resizer; then
          git clone https://github.com/Cykooz/fast_image_resize --depth 1 --single-branch -b v5.1.1
          cargo install --path ./fast_image_resize/resizer
          rm -rf ./fast_image_resize
        fi
    - run: resizer --version
    - run: pipx install gdown
    - run: gdown --version
    - uses: mfinelli/setup-imagemagick@v7
    - run: magick --version | sed -n 1p

    - run: ./ci.sh
